# Translations template for neutron.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the neutron project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: neutron 2015.1.dev699.g6a985c8\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-12-14 06:05+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: neutron/policy.py:108
#, python-format
msgid ""
"Found deprecated policy rule:%s. Please consider upgrading your policy "
"configuration file"
msgstr ""

#: neutron/policy.py:166
#, python-format
msgid "Unable to find data type descriptor for attribute %s"
msgstr ""

#: neutron/quota.py:241
#, python-format
msgid "%s is already registered."
msgstr ""

#: neutron/agent/dhcp_agent.py:134
#, python-format
msgid ""
"Unable to %(action)s dhcp for %(net_id)s: there is a conflict with its "
"current state; please check that the network and/or its subnet(s) still "
"exist."
msgstr ""

#: neutron/agent/dhcp_agent.py:144 neutron/agent/dhcp_agent.py:213
#, python-format
msgid "Network %s has been deleted."
msgstr ""

#: neutron/agent/dhcp_agent.py:230
#, python-format
msgid ""
"Network %s may have been deleted and its resources may have already been "
"disposed."
msgstr ""

#: neutron/agent/dhcp_agent.py:366
#, python-format
msgid ""
"%(port_num)d router ports found on the metadata access network. Only the "
"port %(port_id)s, for router %(router_id)s will be considered"
msgstr ""

#: neutron/agent/dhcp_agent.py:587 neutron/agent/l3/agent.py:1724
#: neutron/agent/metadata/agent.py:411
#: neutron/plugins/cisco/cfg_agent/cfg_agent.py:321
#: neutron/services/metering/agents/metering_agent.py:273
msgid ""
"Neutron server does not support state report. State report for this agent"
" will be disabled."
msgstr ""

#: neutron/agent/rpc.py:101
msgid "DVR functionality requires a server upgrade."
msgstr ""

#: neutron/agent/securitygroups_rpc.py:67
#: neutron/agent/securitygroups_rpc.py:157
msgid "Driver configuration doesn't match with enable_security_group"
msgstr ""

#: neutron/agent/securitygroups_rpc.py:112
msgid ""
"Security group agent binding currently not set. This should be set by the"
" end of the init process."
msgstr ""

#: neutron/agent/securitygroups_rpc.py:184
msgid ""
"security_group_info_for_devices rpc call not supported by the server, "
"falling back to old security_group_rules_for_devices which scales worse."
msgstr ""

#: neutron/agent/l3/agent.py:243
#, python-format
msgid ""
"l3-agent cannot check service plugins enabled at the neutron server when "
"startup due to RPC error. It happens when the server does not support "
"this RPC API. If the error is UnsupportedVersion you can ignore this "
"warning. Detail message: %s"
msgstr ""

#: neutron/agent/l3/agent.py:255
#, python-format
msgid ""
"l3-agent cannot check service plugins enabled on the neutron server. "
"Retrying. Detail message: %s"
msgstr ""

#: neutron/agent/l3/agent.py:485
#, python-format
msgid "Info for router %s were not found. Skipping router removal"
msgstr ""

#: neutron/agent/l3/agent.py:838
#, python-format
msgid "Unable to configure IP address for floating IP: %s"
msgstr ""

#: neutron/agent/linux/iptables_manager.py:155
#, python-format
msgid "Attempted to remove chain %s which does not exist"
msgstr ""

#: neutron/agent/linux/iptables_manager.py:235
#, python-format
msgid ""
"Tried to remove rule that was not there: %(chain)r %(rule)r %(wrap)r "
"%(top)r"
msgstr ""

#: neutron/agent/linux/iptables_manager.py:663
#, python-format
msgid "Attempted to get traffic counters of chain %s which does not exist"
msgstr ""

#: neutron/agent/linux/keepalived.py:361
msgid ""
"A previous instance of keepalived seems to be dead, unable to restart it,"
" a new instance will be spawned"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:349
#, python-format
msgid "Found not yet ready openvswitch port: %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:364
#, python-format
msgid "Found failed openvswitch port: %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:423
#, python-format
msgid "ofport: %(ofport)s for VIF: %(vif)s is not a positive integer"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:435
#, python-format
msgid "Unable to parse interface details. Exception: %s"
msgstr ""

#: neutron/agent/metadata/agent.py:171
msgid "Server does not support metadata RPC, fallback to using neutron client"
msgstr ""

#: neutron/agent/metadata/agent.py:286
msgid ""
"The remote metadata server responded with Forbidden. This response "
"usually occurs when shared secrets do not match."
msgstr ""

#: neutron/api/api_common.py:102
#, python-format
msgid ""
"Invalid value for pagination_max_limit: %s. It should be an integer "
"greater to 0"
msgstr ""

#: neutron/api/extensions.py:543
#, python-format
msgid "Did not find expected name \"%(ext_name)s\" in %(file)s"
msgstr ""

#: neutron/api/extensions.py:551
#, python-format
msgid "Extension file %(f)s wasn't loaded due to %(exception)s"
msgstr ""

#: neutron/api/extensions.py:592
#, python-format
msgid "Extension %s not supported by any of loaded plugins"
msgstr ""

#: neutron/api/extensions.py:604
#, python-format
msgid "Loaded plugins do not implement extension %s interface"
msgstr ""

#: neutron/api/rpc/agentnotifiers/dhcp_rpc_agent_api.py:67
#, python-format
msgid ""
"Unable to schedule network %s: no agents available; will retry on "
"subsequent port creation events."
msgstr ""

#: neutron/api/rpc/agentnotifiers/dhcp_rpc_agent_api.py:80
#, python-format
msgid ""
"Only %(active)d of %(total)d DHCP agents associated with network "
"'%(net_id)s' are marked as active, so notifications may be sent to "
"inactive agents."
msgstr ""

#: neutron/api/rpc/handlers/dhcp_rpc.py:83
#, python-format
msgid ""
"Action %(action)s for network %(net_id)s could not complete successfully:"
" %(reason)s"
msgstr ""

#: neutron/api/rpc/handlers/dhcp_rpc.py:127
#: neutron/api/rpc/handlers/dhcp_rpc.py:191
#, python-format
msgid "Network %s could not be found, it might have been deleted concurrently."
msgstr ""

#: neutron/api/rpc/handlers/dhcp_rpc.py:260
#, python-format
msgid "Updating lease expiration is now deprecated. Issued  from host %s."
msgstr ""

#: neutron/db/agents_db.py:99
#, python-format
msgid "%(agent_type)s agent %(agent_id)s is not active"
msgstr ""

#: neutron/db/agents_db.py:112
#, python-format
msgid "Configuration for agent %(agent_type)s on host %(host)s is invalid."
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:106
msgid ""
"Time since last L3 agent reschedule check has exceeded the interval "
"between checks. Waiting before check to allow agents to send a heartbeat "
"in case there was a clock adjustment."
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:128
#, python-format
msgid ""
"Rescheduling router %(router)s from agent %(agent)s because the agent did"
" not report to the server in the last %(dead_time)s seconds."
msgstr ""

#: neutron/db/l3_dvrscheduler_db.py:298
msgid "No active L3 agents found for SNAT"
msgstr ""

#: neutron/db/l3_hamode_db.py:405
#, python-format
msgid "The router %(router_id)s is bound multiple times on the agent %(host)s"
msgstr ""

#: neutron/db/securitygroups_rpc_base.py:362
#, python-format
msgid "No valid gateway port on subnet %s is found for IPv6 RA"
msgstr ""

#: neutron/debug/debug_agent.py:123
#, python-format
msgid "Failed to delete namespace %s"
msgstr ""

#: neutron/notifiers/nova.py:186
msgid "Port ID not set! Nova will not be notified of port status change."
msgstr ""

#: neutron/notifiers/nova.py:242
#, python-format
msgid "Nova returned NotFound for event: %s"
msgstr ""

#: neutron/notifiers/nova.py:260
#, python-format
msgid "Nova event: %s returned with failed status"
msgstr ""

#: neutron/openstack/common/loopingcall.py:87
#, python-format
msgid "task %(func_name)s run outlasted interval by %(delay).2f sec"
msgstr ""

#: neutron/openstack/common/policy.py:248
#, python-format
msgid "Can not find policy directory: %s"
msgstr ""

#: neutron/openstack/common/service.py:356
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: neutron/plugins/bigswitch/plugin.py:318
#, python-format
msgid ""
"Setting admin_state_up=False is not supported in this plugin version. "
"Ignoring setting for resource: %s"
msgstr ""

#: neutron/plugins/bigswitch/plugin.py:324
#, python-format
msgid ""
"Operational status is internally set by the plugin. Ignoring setting "
"status=%s."
msgstr ""

#: neutron/plugins/bigswitch/plugin.py:349
#, python-format
msgid "Unrecognized vif_type in configuration [%s]. Defaulting to ovs."
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:400
#, python-format
msgid "Storing to certificate for host %(server)s at %(path)s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:514
#, python-format
msgid ""
"NeutronRestProxyV2: Received and ignored error code %(code)s on "
"%(action)s action to resource %(resource)s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:572
#, python-format
msgid "No device MAC attached to port %s. Skipping notification to controller."
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:613
msgid "Backend server(s) do not support automated consitency checks."
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:617
#, python-format
msgid "Consistency watchdog disabled by polling interval setting of %s."
msgstr ""

#: neutron/plugins/bigswitch/db/consistency_db.py:189
#, python-format
msgid ""
"Gave up waiting for consistency DB lock, trying to take it. Current hash "
"is: %s"
msgstr ""

#: neutron/plugins/bigswitch/db/consistency_db.py:205
msgid "Hash record already gone, no lock to clear."
msgstr ""

#: neutron/plugins/bigswitch/db/consistency_db.py:209
#, python-format
msgid "Another server already removed the lock. %s"
msgstr ""

#: neutron/plugins/bigswitch/db/porttracker_db.py:40
msgid "No host_id in port request to track port location."
msgstr ""

#: neutron/plugins/bigswitch/db/porttracker_db.py:43
#, python-format
msgid "Received an empty port ID for host_id '%s'"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_agent.py:130
#, python-format
msgid ""
"Error in loading routing service helper. Class specified is %(class)s. "
"Reason:%(reason)s"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_agent.py:201
msgid "No routing service helper loaded"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_agent.py:278
#, python-format
msgid ""
"[Agent registration] Neutron server said that device manager was not "
"ready. Retrying in %0.2f seconds "
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_status.py:59
#, python-format
msgid "Cannot ping ip address: %s"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_drivers/csr1kv/csr1kv_routing_driver.py:338
#, python-format
msgid "Cannot find interface: %s"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_drivers/csr1kv/csr1kv_routing_driver.py:478
#, python-format
msgid "VRF %s not present"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/service_helpers/routing_svc_helper.py:539
#, python-format
msgid "Info for router %s was not found. Skipping router removal"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/service_helpers/routing_svc_helper.py:554
#, python-format
msgid ""
"Router remove for router_id: %s was incomplete. Adding the router to "
"removed_routers list"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:582
#, python-format
msgid "vlan_id %(vlan)s on physical network %(network)s not found"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:659
#, python-format
msgid "vxlan_id %s not found"
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:329
#, python-format
msgid "Cisco cfg agent %s is not alive"
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:463
msgid "There are no active Cisco cfg agents"
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:284
#, python-format
msgid "Aborting resource deletion after %d unsuccessful attempts"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:173
msgid "No policy profile populated from VSM"
msgstr ""

#: neutron/plugins/embrane/agent/operations/router_operations.py:96
#, python-format
msgid "The router %s had no physical representation,likely already deleted"
msgstr ""

#: neutron/plugins/embrane/agent/operations/router_operations.py:125
#, python-format
msgid "Interface %s not found in the heleos back-end,likely already deleted"
msgstr ""

#: neutron/plugins/hyperv/db.py:138
#, python-format
msgid "vlan_id %(vlan_id)s on physical network %(physical_network)s not found"
msgstr ""

#: neutron/plugins/hyperv/agent/utilsfactory.py:61
msgid ""
"V1 virtualization namespace no longer supported on Windows Server / "
"Hyper-V Server 2012 R2 or above."
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:428
#, python-format
msgid "Ignoring admin_state_up=False for router=%r.  Overriding with True"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:83
msgid "VXLAN is enabled, a valid local_ip must be provided"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:97
msgid "Invalid Network ID, will lead to incorrect bridgename"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:104
msgid "Invalid VLAN ID, will lead to incorrect subinterface name"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:111
msgid "Invalid Interface ID, will lead to incorrect tap device name"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:120
#, python-format
msgid "Invalid Segmentation ID: %s, will lead to incorrect vxlan device name"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:520
#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:556
#, python-format
msgid ""
"Option \"%(option)s\" must be supported by command \"%(command)s\" to "
"enable %(mode)s mode"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:550
msgid ""
"VXLAN muticast group must be provided in vxlan_group option to enable "
"VXLAN MCAST mode"
msgstr ""

#: neutron/plugins/metaplugin/proxy_neutron_plugin.py:74
msgid "Subnet in remote have already deleted"
msgstr ""

#: neutron/plugins/metaplugin/proxy_neutron_plugin.py:102
msgid "Network in remote have already deleted"
msgstr ""

#: neutron/plugins/metaplugin/proxy_neutron_plugin.py:134
msgid "Port in remote have already deleted"
msgstr ""

#: neutron/plugins/midonet/midonet_lib.py:174
msgid "Tried to delete mapping from non-existent subnet"
msgstr ""

#: neutron/plugins/midonet/midonet_lib.py:393
#, python-format
msgid "Attempted to unlink a port that was not linked. %s"
msgstr ""

#: neutron/plugins/midonet/plugin.py:1022
msgid ""
"DHCP agent is not working correctly. No port to reach the Metadata server"
" on this network"
msgstr ""

#: neutron/plugins/ml2/managers.py:601
#, python-format
msgid "Failed to bind port %(port)s on host %(host)s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:478
#, python-format
msgid ""
"In _notify_port_updated(), no bound segment for port %(port_id)s on "
"network %(network_id)s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:639
msgid "A concurrent port creation has occurred"
msgstr ""

#: neutron/plugins/ml2/plugin.py:1114
#, python-format
msgid "Port %(port)s updated up by agent not found"
msgstr ""

#: neutron/plugins/ml2/plugin.py:1144
#, python-format
msgid "Port %s not found during update"
msgstr ""

#: neutron/plugins/ml2/rpc.py:68
#, python-format
msgid "Device %(device)s requested by agent %(agent_id)s not found in database"
msgstr ""

#: neutron/plugins/ml2/rpc.py:77
#, python-format
msgid ""
"Device %(device)s requested by agent %(agent_id)s on network "
"%(network_id)s not bound, vif_type: %(vif_type)s"
msgstr ""

#: neutron/plugins/ml2/drivers/helpers.py:141
#, python-format
msgid ""
"Allocate %(type)s segment from pool failed after %(number)s failed "
"attempts"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_agent.py:74
#: neutron/plugins/ml2/drivers/mech_sriov/mech_driver.py:113
#, python-format
msgid "Attempting to bind with dead agent: %s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_flat.py:131
#, python-format
msgid "No flat network found on physical network %s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_gre.py:132
#, python-format
msgid "Gre endpoint with ip %s already exists"
msgstr ""

#: neutron/plugins/ml2/drivers/type_tunnel.py:142
#, python-format
msgid "%(type)s tunnel %(id)s not found"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vlan.py:253
#, python-format
msgid "No vlan_id %(vlan_id)s found on physical network %(physical_network)s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vxlan.py:151
#, python-format
msgid "Vxlan endpoint with ip %s already exists"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/mechanism_arista.py:77
#, python-format
msgid "'timestamp' command '%s' is not available on EOS"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/mechanism_arista.py:331
#, python-format
msgid "VM id %(vmid)s not found for port %(portid)s"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/mechanism_arista.py:348
#, python-format
msgid "Unknown device owner: %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:66
#, python-format
msgid "Create network postcommit failed for network %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:76
#, python-format
msgid "Create subnet postcommit failed for subnet %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:89
#, python-format
msgid "Create port postcommit failed for port %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:108
#, python-format
msgid "Add interface postcommit failed for port %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/nexus/nexus_db_v2.py:75
msgid "update_nexusport_binding called with no vlan"
msgstr ""

#: neutron/plugins/ml2/drivers/l2pop/mech_driver.py:155
msgid "Unable to retrieve the agent ip, check the agent configuration."
msgstr ""

#: neutron/plugins/ml2/drivers/l2pop/mech_driver.py:161
#, python-format
msgid "Port %(port)s updated by agent %(agent)s isn't bound to any segment"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_bigswitch/driver.py:138
msgid "Ignoring port notification to controller because of missing host ID."
msgstr ""

#: neutron/plugins/mlnx/agent/eswitch_neutron_agent.py:165
msgid "Invalid Network ID, cannot remove Network"
msgstr ""

#: neutron/plugins/mlnx/db/mlnx_db_v2.py:182
#, python-format
msgid "vlan_id %(seg_id)s on physical network %(phy_net)s not found"
msgstr ""

#: neutron/plugins/nec/nec_plugin.py:212
#, python-format
msgid "delete_ofc_tenant() failed due to %s"
msgstr ""

#: neutron/plugins/nec/nec_router.py:312
#, python-format
msgid ""
"OFC does not support router with provider=%(provider)s, so removed it "
"from supported provider (new router driver map=%(driver_map)s)"
msgstr ""

#: neutron/plugins/nec/router_drivers.py:178
#, python-format
msgid ""
"RouterOpenFlowDriver.add_interface(): the requested port has no subnet. "
"add_interface() is skipped. router_id=%(id)s, port=%(port)s)"
msgstr ""

#: neutron/plugins/nec/common/ofc_client.py:104
#, python-format
msgid "OFC returns ServiceUnavailable (retry-after=%s)"
msgstr ""

#: neutron/plugins/nec/common/ofc_client.py:112
#, python-format
msgid "Operation on OFC failed: status=%(status)s, detail=%(detail)s"
msgstr ""

#: neutron/plugins/nec/db/api.py:103
#, python-format
msgid "del_ofc_item(): NotFound item (resource=%(resource)s, id=%(id)s) "
msgstr ""

#: neutron/plugins/nec/db/api.py:137
#, python-format
msgid "del_portinfo(): NotFound portinfo for port_id: %s"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:298
#, python-format
msgid "Subnet %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:316
#, python-format
msgid "Router %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:328
#, python-format
msgid ""
"Route with destination %(dest)s and nexthop %(hop)s not found in neutron "
"for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:342
#, python-format
msgid "Security group %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:353
#, python-format
msgid "Security group rule %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:363
#, python-format
msgid "Floating ip %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:375
#, python-format
msgid "IP allocation for floating ip %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:386
#, python-format
msgid "Net-partition %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:396
#, python-format
msgid "VM port %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:283
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1300
#, python-format
msgid "Unable to create tunnel port. Invalid remote IP: %s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:639
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1022
#, python-format
msgid "VIF port: %s has no ofport configured, and might not be able to transmit"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:746
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1145
#, python-format
msgid "Device %s not defined on plugin"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:110
msgid "No Token, Re-login"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:154
#, python-format
msgid ""
"L2 agent could not get DVR MAC address at startup due to RPC error.  It "
"happens when the server does not support this RPC API.  Detailed message:"
" %s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:180
#, python-format
msgid ""
"L2 agent could not get DVR MAC address from server. Retrying. Detailed "
"message: %s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:450
#, python-format
msgid "Action %s not supported"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:862
#, python-format
msgid ""
"Creating an interface named %(name)s exceeds the %(limit)d character "
"limitation. It was shortened to %(new_name)s to fit."
msgstr ""

#: neutron/plugins/plumgrid/plumgrid_plugin/plumgrid_plugin.py:769
msgid ""
"Networks with admin_state_up=False are not supported by PLUMgrid plugin "
"yet."
msgstr ""

#: neutron/plugins/sriovnicagent/eswitch_manager.py:148
#: neutron/plugins/sriovnicagent/eswitch_manager.py:161
#, python-format
msgid "Cannot find vf index for pci slot %s"
msgstr ""

#: neutron/plugins/sriovnicagent/eswitch_manager.py:286
#, python-format
msgid "device pci mismatch: %(device_mac)s - %(pci_slot)s"
msgstr ""

#: neutron/plugins/sriovnicagent/pci_lib.py:127
#, python-format
msgid "Cannot find vfs %(vfs)s in device %(dev_name)s"
msgstr ""

#: neutron/plugins/sriovnicagent/pci_lib.py:143
#, python-format
msgid "failed to parse vf link show line %(line)s: for %(device)s"
msgstr ""

#: neutron/plugins/vmware/dhcpmeta_modes.py:110
msgid "network_auto_schedule has been disabled"
msgstr ""

#: neutron/plugins/vmware/api_client/base.py:104
#, python-format
msgid "[%d] no API providers currently available."
msgstr ""

#: neutron/plugins/vmware/api_client/base.py:152
#, python-format
msgid "[%(rid)d] Connection returned in bad state, reconnecting to %(conn)s"
msgstr ""

#: neutron/plugins/vmware/api_client/eventlet_request.py:214
#, python-format
msgid "[%(rid)d] Failed to parse API provider: %(e)s"
msgstr ""

#: neutron/plugins/vmware/api_client/request.py:124
#, python-format
msgid "[%(rid)d] Exception issuing request: %(e)s"
msgstr ""

#: neutron/plugins/vmware/api_client/request.py:191
#, python-format
msgid "[%(rid)d] Request '%(method)s %(url)s' received: %(status)s"
msgstr ""

#: neutron/plugins/vmware/api_client/request.py:204
#, python-format
msgid "[%(rid)d] Failed request '%(conn)s': '%(msg)s' (%(elapsed)s seconds)"
msgstr ""

#: neutron/plugins/vmware/api_client/request.py:238
#, python-format
msgid "[%d] Received redirect status without location header field"
msgstr ""

#: neutron/plugins/vmware/api_client/request.py:255
#, python-format
msgid "[%(rid)d] Received invalid redirect location: '%(url)s'"
msgstr ""

#: neutron/plugins/vmware/api_client/request.py:259
#, python-format
msgid "[%(rid)d] Received malformed redirect location: %(url)s"
msgstr ""

#: neutron/plugins/vmware/api_client/version.py:31
#, python-format
msgid "Unable to fetch NSX version from response headers :%s"
msgstr ""

#: neutron/plugins/vmware/common/nsx_utils.py:68
#, python-format
msgid "Unable to find NSX switches for Neutron network %s"
msgstr ""

#: neutron/plugins/vmware/common/nsx_utils.py:115
#, python-format
msgid "Unable to find NSX port for Neutron port %s"
msgstr ""

#: neutron/plugins/vmware/common/nsx_utils.py:155
#, python-format
msgid "Unable to find NSX security profile for Neutron security group %s"
msgstr ""

#: neutron/plugins/vmware/common/nsx_utils.py:159
#, python-format
msgid "Multiple NSX security profiles found for Neutron security group %s"
msgstr ""

#: neutron/plugins/vmware/common/nsx_utils.py:190
#, python-format
msgid "Unable to find NSX router for Neutron router %s"
msgstr ""

#: neutron/plugins/vmware/common/nsx_utils.py:247
#, python-format
msgid ""
"Unable to retrieve operational status for gateway devices belonging to "
"tenant: %s"
msgstr ""

#: neutron/plugins/vmware/common/nsx_utils.py:250
msgid "Unable to retrieve operational status for gateway devices"
msgstr ""

#: neutron/plugins/vmware/common/sync.py:266
#, python-format
msgid "Logical switch for neutron network %s not found on NSX."
msgstr ""

#: neutron/plugins/vmware/common/sync.py:353
#, python-format
msgid "Logical router for neutron router %s not found on NSX."
msgstr ""

#: neutron/plugins/vmware/common/sync.py:403
#, python-format
msgid "Unable to find Neutron router id for NSX logical router: %s"
msgstr ""

#: neutron/plugins/vmware/common/sync.py:445
#, python-format
msgid "Logical switch port for neutron port %s not found on NSX."
msgstr ""

#: neutron/plugins/vmware/common/sync.py:538
#, python-format
msgid ""
"Requested page size is %(cur_chunk_size)d. It might be necessary to do "
"%(num_requests)d round-trips to NSX for fetching data. Please tune sync "
"parameters to ensure chunk size is less than %(max_page_size)d"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:78
#, python-format
msgid "Unable to find Logical Service Node for the requested network %s."
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:95
#, python-format
msgid "Unable to delete Logical Service Node %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:120
#, python-format
msgid ""
"Unable to find Logical Service Node Port for LSN %(lsn_id)s and subnet "
"%(subnet_id)s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:147
#, python-format
msgid ""
"Unable to find Logical Service Node Port for LSN %(lsn_id)s and mac "
"address %(mac)s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:172
#, python-format
msgid "Unable to delete LSN Port %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:189
#, python-format
msgid "Metadata port not found while attempting to delete it from network %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:192
#, python-format
msgid "Unable to find Logical Services Node Port with MAC %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/rpc.py:96
msgid ""
"Overlapping IPs must be enabled in order to setup the metadata access "
"network"
msgstr ""

#: neutron/plugins/vmware/nsxlib/router.py:581
#, python-format
msgid ""
"Found %(actual_rule_num)d matching NAT rules, which is not in the "
"expected range (%(min_exp_rule_num)d,%(max_exp_rule_num)d)"
msgstr ""

#: neutron/plugins/vmware/nsxlib/secgroup.py:142
#, python-format
msgid "Unable to find security profile %s on NSX backend"
msgstr ""

#: neutron/plugins/vmware/nsxlib/switch.py:248
#, python-format
msgid "Lswitch %s not found in NSX"
msgstr ""

#: neutron/plugins/vmware/nsxlib/switch.py:282
#, python-format
msgid ""
"Found '%(num_ports)d' ports with q_port_id tag: '%(neutron_port_id)s'. "
"Only 1 was expected."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:475
#, python-format
msgid ""
"Concurrent network deletion detected; Back-end Port %(nsx_id)s creation "
"to be rolled back for Neutron port: %(neutron_id)s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:513
#, python-format
msgid "Port %s not found in NSX"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:523
#, python-format
msgid ""
"Neutron port %(port_id)s not found on NSX backend. Terminating delete "
"operation. A dangling router port might have been left on router "
"%(router_id)s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:938
#, python-format
msgid ""
"Network with admin_state_up=False are not yet supported by this plugin. "
"Ignoring setting for network %s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1017
#, python-format
msgid "The following logical switches were not found on the NSX backend:%s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1074
#, python-format
msgid "Unable to find NSX mappings for neutron network:%s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1081
#, python-format
msgid ""
"Logical switch update on NSX backend failed. Neutron network "
"id:%(net_id)s; NSX lswitch id:%(lswitch_id)s;Error:%(error)s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1161
#, python-format
msgid "Logical switch for network %s was not found in NSX."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1484
#, python-format
msgid "Failed to set gateway info for router being created:%s - removing router"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1608
#, python-format
msgid "Logical router '%s' not found on NSX Platform"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1622
#, python-format
msgid ""
"Unable to remove NSX mapping for Neutron router %(router_id)s because of "
"the following exception:%(d_exc)s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1801
msgid "An incorrect number of matching NAT rules was found on the NSX platform"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1991
#, python-format
msgid "Nat rules not found in nsx for port: %s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2084
#, python-format
msgid "Unable to update name on NSX backend for network gateway: %s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2291
#, python-format
msgid ""
"Removal of gateway device: %(neutron_id)s failed on NSX backend (NSX "
"id:%(nsx_id)s) because the NSX resource was not found"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2378
#, python-format
msgid ""
"The NSX security profile %(sec_profile_id)s, associated with the Neutron "
"security group %(sec_group_id)s was not found on the backend"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:551
#, python-format
msgid "Did not found lswitch %s in NSX"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_ipsecvpn_driver.py:66
msgid ""
"IKEPolicy and IPsecPolicy should have consistent auth_algorithm, "
"encryption_algorithm and pfs for VSE!"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_ipsecvpn_driver.py:146
#, python-format
msgid "IPsec config not found on edge: %s"
msgstr ""

#: neutron/scheduler/dhcp_agent_scheduler.py:80
#: neutron/scheduler/dhcp_agent_scheduler.py:89
msgid "No more DHCP agents"
msgstr ""

#: neutron/scheduler/dhcp_agent_scheduler.py:120
#, python-format
msgid "DHCP agent %s is not active"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:156
#, python-format
msgid "No routers compatible with L3 agent configuration on host %s"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:181
msgid "No active L3 agents"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:193
#, python-format
msgid "No L3 agents can host the router %s"
msgstr ""

