# Translations template for neutron.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the neutron project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: neutron 2015.1.dev699.g6a985c8\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-12-14 06:05+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: neutron/manager.py:138
#, python-format
msgid "Error loading plugin by name, %s"
msgstr ""

#: neutron/manager.py:139
#, python-format
msgid "Error loading plugin by class, %s"
msgstr ""

#: neutron/policy.py:129
#, python-format
msgid ""
"Backward compatibility unavailable for deprecated policy %s. The policy "
"will not be enforced"
msgstr ""

#: neutron/policy.py:317
#, python-format
msgid "Policy check error while calling %s!"
msgstr ""

#: neutron/service.py:106 neutron/service.py:164
msgid "Unrecoverable error: please check log for details."
msgstr ""

#: neutron/service.py:147
#, python-format
msgid "'rpc_workers = %d' ignored because start_rpc_listeners is not implemented."
msgstr ""

#: neutron/service.py:171
msgid "No known API applications configured."
msgstr ""

#: neutron/service.py:278
msgid "Exception occurs when timer stops"
msgstr ""

#: neutron/service.py:287
msgid "Exception occurs when waiting for timer"
msgstr ""

#: neutron/wsgi.py:130
#, python-format
msgid "Unable to listen on %(host)s:%(port)s"
msgstr ""

#: neutron/wsgi.py:770
#, python-format
msgid "InvalidContentType: %s"
msgstr ""

#: neutron/wsgi.py:774
#, python-format
msgid "MalformedRequestBody: %s"
msgstr ""

#: neutron/wsgi.py:783
msgid "Internal error"
msgstr ""

#: neutron/agent/dhcp_agent.py:146
#, python-format
msgid "Unable to %(action)s dhcp for %(net_id)s."
msgstr ""

#: neutron/agent/dhcp_agent.py:173
#, python-format
msgid "Unable to sync network state on deleted network %s"
msgstr ""

#: neutron/agent/dhcp_agent.py:186
msgid "Unable to sync network state."
msgstr ""

#: neutron/agent/dhcp_agent.py:217
#, python-format
msgid "Network %s info call failed."
msgstr ""

#: neutron/agent/dhcp_agent.py:593 neutron/agent/l3/agent.py:1729
#: neutron/agent/metadata/agent.py:416
#: neutron/plugins/hyperv/agent/hyperv_neutron_agent.py:148
#: neutron/plugins/ibm/agent/sdnve_neutron_agent.py:110
#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:794
#: neutron/plugins/mlnx/agent/eswitch_neutron_agent.py:213
#: neutron/plugins/nec/agent/nec_neutron_agent.py:179
#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:276
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:276
#: neutron/plugins/sriovnicagent/sriov_nic_agent.py:131
#: neutron/services/metering/agents/metering_agent.py:278
msgid "Failed reporting state!"
msgstr ""

#: neutron/agent/netns_cleanup_util.py:141
#, python-format
msgid "Error unable to destroy namespace: %s"
msgstr ""

#: neutron/agent/l3/agent.py:222 neutron/tests/unit/test_l3_agent.py:1786
#, python-format
msgid "Error importing interface driver '%s'"
msgstr ""

#: neutron/agent/l3/agent.py:294 neutron/agent/linux/dhcp.py:809
msgid "An interface driver must be specified"
msgstr ""

#: neutron/agent/l3/agent.py:299
msgid "Router id is required if not using namespaces."
msgstr ""

#: neutron/agent/l3/agent.py:317
msgid "RuntimeError in obtaining router list for namespace cleanup."
msgstr ""

#: neutron/agent/l3/agent.py:342
#, python-format
msgid "Failed to destroy stale router namespace %s"
msgstr ""

#: neutron/agent/l3/agent.py:358 neutron/agent/linux/dhcp.py:238
#, python-format
msgid "Failed trying to delete namespace: %s"
msgstr ""

#: neutron/agent/l3/agent.py:560
#: neutron/plugins/cisco/cfg_agent/service_helpers/routing_svc_helper.py:632
#, python-format
msgid "Ignoring multiple IPs on router port %s"
msgstr ""

#: neutron/agent/l3/agent.py:921
#, python-format
msgid "Failed sending gratuitous ARP: %s"
msgstr ""

#: neutron/agent/l3/agent.py:996
msgid "DVR: no map match_port found!"
msgstr ""

#: neutron/agent/l3/agent.py:1201
msgid "DVR: error adding redirection logic"
msgstr ""

#: neutron/agent/l3/agent.py:1213
msgid "DVR: removed snat failed"
msgstr ""

#: neutron/agent/l3/agent.py:1309
msgid "Missing subnet/agent_gateway_port"
msgstr ""

#: neutron/agent/l3/agent.py:1454
msgid "DVR: Failed updating arp entry"
msgstr ""

#: neutron/agent/l3/agent.py:1505
#, python-format
msgid "The external network bridge '%s' does not exist"
msgstr ""

#: neutron/agent/l3/agent.py:1545
#, python-format
msgid "Failed to fetch router information for '%s'"
msgstr ""

#: neutron/agent/l3/agent.py:1563
#, python-format
msgid "Removing incompatible router '%s'"
msgstr ""

#: neutron/agent/l3/agent.py:1600
msgid "Failed synchronizing routers due to RPC error"
msgstr ""

#: neutron/agent/l3/agent.py:1603
#: neutron/services/metering/agents/metering_agent.py:62
msgid "Failed synchronizing routers"
msgstr ""

#: neutron/agent/l3/ha.py:136
#, python-format
msgid "Unable to process HA router %s without ha port"
msgstr ""

#: neutron/agent/linux/async_process.py:164
#, python-format
msgid "An error occurred while killing [%s]."
msgstr ""

#: neutron/agent/linux/async_process.py:186
#, python-format
msgid "An error occurred while communicating with async process [%s]."
msgstr ""

#: neutron/agent/linux/daemon.py:36
#, python-format
msgid "Error while handling pidfile: %s"
msgstr ""

#: neutron/agent/linux/daemon.py:93
msgid "Fork failed"
msgstr ""

#: neutron/agent/linux/daemon.py:135
#, python-format
msgid "Pidfile %s already exist. Daemon already running?"
msgstr ""

#: neutron/agent/linux/dhcp.py:329
#, python-format
msgid ""
"FAILED VERSION REQUIREMENT FOR DNSMASQ. DHCP AGENT MAY NOT RUN CORRECTLY!"
" Please ensure that its version is %s or above!"
msgstr ""

#: neutron/agent/linux/dhcp.py:335
#, python-format
msgid ""
"Unable to determine dnsmasq version. Please ensure that its version is %s"
" or above!"
msgstr ""

#: neutron/agent/linux/dhcp.py:815
#, python-format
msgid "Error importing interface driver '%(driver)s': %(inner)s"
msgstr ""

#: neutron/agent/linux/external_process.py:230
#, python-format
msgid ""
"%(service)s for %(resource_type)s with uuid %(uuid)s not found. The "
"process should not have died"
msgstr ""

#: neutron/agent/linux/external_process.py:250
#, python-format
msgid "respawning %(service)s for uuid %(uuid)s"
msgstr ""

#: neutron/agent/linux/external_process.py:256
msgid "Exiting agent as programmed in check_child_processes_actions"
msgstr ""

#: neutron/agent/linux/interface.py:154
#, python-format
msgid "Failed deleting ingress connection state of floatingip %s"
msgstr ""

#: neutron/agent/linux/interface.py:163
#, python-format
msgid "Failed deleting egress connection state of floatingip %s"
msgstr ""

#: neutron/agent/linux/interface.py:282 neutron/agent/linux/interface.py:327
#: neutron/agent/linux/interface.py:394 neutron/agent/linux/interface.py:436
#, python-format
msgid "Failed unplugging interface '%s'"
msgstr ""

#: neutron/agent/linux/ip_link_support.py:107
#: neutron/plugins/sriovnicagent/pci_lib.py:57
#: neutron/plugins/sriovnicagent/pci_lib.py:79
#: neutron/plugins/sriovnicagent/pci_lib.py:106
msgid "Failed executing ip command"
msgstr ""

#: neutron/agent/linux/iptables_manager.py:446
#, python-format
msgid ""
"IPTablesManager.apply failed to apply the following set of iptables "
"rules:\n"
"%s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:73 neutron/agent/linux/ovs_lib.py:180
#: neutron/agent/linux/ovs_lib.py:301
#: neutron/plugins/bigswitch/agent/restproxy_agent.py:55
#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:252
msgid ""
"Unable to create VXLAN tunnel port. Please ensure that an openvswitch "
"version that supports VXLAN is installed."
msgstr ""

#: neutron/agent/linux/ovs_lib.py:532
#, python-format
msgid "OVS flows could not be applied on bridge %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:542
#, python-format
msgid "Interface %s not found."
msgstr ""

#: neutron/agent/linux/ovs_lib.py:553
#, python-format
msgid "Unable to retrieve bridges. Exception: %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:562
#, python-format
msgid "Bridge %s not found."
msgstr ""

#: neutron/agent/linux/ovsdb_monitor.py:51
#, python-format
msgid "Error received from ovsdb monitor: %s"
msgstr ""

#: neutron/agent/metadata/agent.py:156
#: neutron/agent/metadata/namespace_proxy.py:75
msgid "Unexpected error."
msgstr ""

#: neutron/api/extensions.py:483
#, python-format
msgid "Error fetching extended attributes for extension '%s'"
msgstr ""

#: neutron/api/extensions.py:492
#, python-format
msgid ""
"It was impossible to process the following extensions: %s because of "
"missing requirements."
msgstr ""

#: neutron/api/extensions.py:509
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: neutron/api/extensions.py:527
#, python-format
msgid "Extension path '%s' doesn't exist!"
msgstr ""

#: neutron/api/rpc/agentnotifiers/dhcp_rpc_agent_api.py:92
#, python-format
msgid ""
"Will not send event %(method)s for network %(net_id)s: no agent "
"available. Payload: %(payload)s"
msgstr ""

#: neutron/api/rpc/agentnotifiers/l3_rpc_agent_api.py:105
#, python-format
msgid ""
"No plugin for L3 routing registered. Cannot notify agents with the "
"message %s"
msgstr ""

#: neutron/api/rpc/handlers/l3_rpc.py:71
msgid ""
"No plugin for L3 routing registered! Will reply to l3 agent with empty "
"router dictionary."
msgstr ""

#: neutron/api/v2/base.py:364
#, python-format
msgid "Unable to undo add for %(resource)s %(id)s"
msgstr ""

#: neutron/api/v2/resource.py:97 neutron/api/v2/resource.py:105
#: neutron/api/v2/resource.py:125
#, python-format
msgid "%s failed"
msgstr ""

#: neutron/cmd/sanity_check.py:41
msgid ""
"Check for Open vSwitch VXLAN support failed. Please ensure that the "
"version of openvswitch being used has VXLAN support."
msgstr ""

#: neutron/cmd/sanity_check.py:50
msgid ""
"Check for Open vSwitch patch port support failed. Please ensure that the "
"version of openvswitch being used has patch port support or disable "
"features requiring patch ports (gre/vxlan, etc.)."
msgstr ""

#: neutron/cmd/sanity_check.py:60
msgid ""
"Nova notifications are enabled, but novaclient is not installed. Either "
"disable nova notifications or install python-novaclient."
msgstr ""

#: neutron/cmd/sanity_check.py:70
msgid ""
"Check for Open vSwitch ARP responder support failed. Please ensure that "
"the version of openvswitch being used has ARP flows support."
msgstr ""

#: neutron/cmd/sanity_check.py:80
msgid ""
"Check for VF management support failed. Please ensure that the version of"
" ip link being used has VF support."
msgstr ""

#: neutron/cmd/sanity/checks.py:74
#, python-format
msgid "Unexpected exception while checking supported feature via command: %s"
msgstr ""

#: neutron/cmd/sanity/checks.py:106
msgid "Unexpected exception while checking supported ip link command"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:152
#, python-format
msgid "Unable to generate mac address after %s attempts"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:895
#, python-format
msgid "An exception occurred while creating the %(resource)s:%(item)s"
msgstr ""

#: neutron/db/dvr_mac_db.py:97
#, python-format
msgid "MAC generation error after %s attempts"
msgstr ""

#: neutron/db/dvr_mac_db.py:169
#, python-format
msgid "Could not retrieve gateway port for subnet %s"
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:141
#, python-format
msgid "Failed to reschedule router %s"
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:146
msgid "Exception encountered during router rescheduling."
msgstr ""

#: neutron/db/metering/metering_rpc.py:47
#, python-format
msgid "Unable to find agent %s."
msgstr ""

#: neutron/extensions/l3agentscheduler.py:49
#: neutron/extensions/l3agentscheduler.py:92
msgid "No plugin for L3 routing registered to handle router scheduling"
msgstr ""

#: neutron/notifiers/nova.py:245
#, python-format
msgid "Failed to notify nova on events: %s"
msgstr ""

#: neutron/notifiers/nova.py:249 neutron/notifiers/nova.py:265
#, python-format
msgid "Error response returned from nova: %s"
msgstr ""

#: neutron/openstack/common/lockutils.py:117
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: neutron/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr ""

#: neutron/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: neutron/openstack/common/periodic_task.py:208
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: neutron/openstack/common/policy.py:535
#: neutron/openstack/common/policy.py:815
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: neutron/openstack/common/policy.py:545
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: neutron/openstack/common/service.py:269
msgid "Unhandled exception"
msgstr ""

#: neutron/plugins/bigswitch/l3_router_plugin.py:218
#, python-format
msgid "NeutronRestProxyV2: Unable to create remote floating IP: %s"
msgstr ""

#: neutron/plugins/bigswitch/l3_router_plugin.py:287
msgid "NeutronRestProxyV2: too many external networks"
msgstr ""

#: neutron/plugins/bigswitch/plugin.py:398
msgid "Iconsistency with backend controller triggering full synchronization."
msgstr ""

#: neutron/plugins/bigswitch/plugin.py:415
#, python-format
msgid "NeutronRestProxyV2: Unable to create port: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:118
msgid "Couldn't retrieve capabilities. Newer API calls won't be supported."
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:172
msgid "ServerProxy: Could not establish HTTPS connection"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:180
msgid "ServerProxy: Could not establish HTTP connection"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:222
#, python-format
msgid "ServerProxy: %(action)s failure, %(e)r"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:469
#, python-format
msgid ""
"ServerProxy: %(action)s failure for servers: %(server)r Response: "
"%(response)s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:475
#, python-format
msgid ""
"ServerProxy: Error details: status=%(status)d, reason=%(reason)r, "
"ret=%(ret)s, data=%(data)r"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:489
#, python-format
msgid "ServerProxy: %(action)s failure for all servers: %(server)r"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:629
msgid "Encountered an error checking controller health."
msgstr ""

#: neutron/plugins/bigswitch/agent/restproxy_agent.py:154
#: neutron/plugins/hyperv/agent/hyperv_neutron_agent.py:448
#: neutron/plugins/mlnx/agent/eswitch_neutron_agent.py:383
#: neutron/plugins/nec/agent/nec_neutron_agent.py:222
#: neutron/plugins/oneconvergence/agent/nvsd_neutron_agent.py:159
msgid "Error in agent event loop"
msgstr ""

#: neutron/plugins/brocade/NeutronPlugin.py:296
#: neutron/plugins/brocade/NeutronPlugin.py:340
#: neutron/plugins/brocade/NeutronPlugin.py:393
#: neutron/plugins/brocade/NeutronPlugin.py:423
msgid "Brocade NOS driver error"
msgstr ""

#: neutron/plugins/brocade/nos/nosdriver.py:66
#, python-format
msgid "Connect failed to switch: %s"
msgstr ""

#: neutron/plugins/brocade/nos/nosdriver.py:93
#: neutron/plugins/brocade/nos/nosdriver.py:107
#: neutron/plugins/brocade/nos/nosdriver.py:120
#: neutron/plugins/brocade/nos/nosdriver.py:133
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:328
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:339
#, python-format
msgid "NETCONF error: %s"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_agent.py:230
#, python-format
msgid ""
"Invalid payload format for received RPC message "
"`hosting_devices_removed`. Error is %{error}s. Payload is %(payload)s"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_agent.py:283
msgid ""
"[Agent registration] Neutron server said that no device manager was "
"found. Cannot continue. Exiting!"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_agent.py:287
#, python-format
msgid "[Agent registration] %d unsuccessful registration attempts. Exiting!"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_agent.py:326
msgid "Failed sending agent report!"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_drivers/driver_mgr.py:81
#, python-format
msgid ""
"Error loading cfg agent driver %(driver)s for hosting device template "
"%(t_name)s(%(t_id)s)"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_drivers/csr1kv/csr1kv_routing_driver.py:63
#, python-format
msgid "Missing device parameter:%s. Aborting CSR1kvRoutingDriver initialization"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_drivers/csr1kv/csr1kv_routing_driver.py:229
#, python-format
msgid "Unknown route command %s"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_drivers/csr1kv/csr1kv_routing_driver.py:437
#, python-format
msgid "Mismatch in ACL configuration for %s"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_drivers/csr1kv/csr1kv_routing_driver.py:468
#, python-format
msgid "Failed creating VRF %s"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_drivers/csr1kv/csr1kv_routing_driver.py:482
#: neutron/plugins/cisco/cfg_agent/device_drivers/csr1kv/csr1kv_routing_driver.py:495
#, python-format
msgid "VRF %s not present"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/service_helpers/routing_svc_helper.py:224
msgid "Failed processing routers"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/service_helpers/routing_svc_helper.py:285
msgid "RPC Error in fetching routers from plugin"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/service_helpers/routing_svc_helper.py:381
#, python-format
msgid "Key Error, missing key: %s"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/service_helpers/routing_svc_helper.py:385
#, python-format
msgid "Driver Exception on router:%(id)s. Error is %(e)s"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/service_helpers/routing_svc_helper.py:396
#, python-format
msgid "Exception in processing routers on device:%s"
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:123
#, python-format
msgid "No tenant with a name or ID of %s exists."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:126
#, python-format
msgid "Multiple tenants matches found for %s"
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:145
msgid "The virtual management network has no subnet. Please assign one."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:155
msgid ""
"The virtual management network does not have unique name. Please ensure "
"that it is."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:159
msgid "There is no virtual management network. Please create one."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:181
msgid ""
"The security group for the virtual management network does not have "
"unique name. Please ensure that it is."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:186
msgid ""
"There is no security group for the virtual management network. Please "
"create one."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:200
msgid "Error loading hosting device driver"
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:213
msgid "Error loading plugging driver"
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:422
#, python-format
msgid "Failed to delete hosting device %s service VM. Will un-register it anyway."
msgstr ""

#: neutron/plugins/cisco/db/l3/l3_router_appliance_db.py:410
#, python-format
msgid "DB inconsistency: No type and hosting info associated with router %s"
msgstr ""

#: neutron/plugins/cisco/db/l3/l3_router_appliance_db.py:415
#, python-format
msgid "DB inconsistency: Multiple type and hosting info associated with router %s"
msgstr ""

#: neutron/plugins/cisco/db/l3/l3_router_appliance_db.py:438
#, python-format
msgid "DB inconsistency: No hosting info associated with router %s"
msgstr ""

#: neutron/plugins/cisco/db/l3/l3_router_appliance_db.py:515
#, python-format
msgid "Failed to allocate hosting port for port %s"
msgstr ""

#: neutron/plugins/cisco/l3/service_vm_lib.py:68
#, python-format
msgid "Failure determining running Nova services: %s"
msgstr ""

#: neutron/plugins/cisco/l3/service_vm_lib.py:85
#, python-format
msgid "Failed to get status of service VM instance %(id)s, due to %(err)s"
msgstr ""

#: neutron/plugins/cisco/l3/service_vm_lib.py:101
#, python-format
msgid "Failure finding needed Nova resource: %s"
msgstr ""

#: neutron/plugins/cisco/l3/service_vm_lib.py:123
#, python-format
msgid "Failed to create service VM instance: %s"
msgstr ""

#: neutron/plugins/cisco/l3/service_vm_lib.py:139
#, python-format
msgid "Failed to delete service VM instance %(id)s, due to %(err)s"
msgstr ""

#: neutron/plugins/cisco/l3/hosting_device_drivers/csr1kv_hd_driver.py:67
#, python-format
msgid "Failed to create config file: %s. Trying toclean up."
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:108
#, python-format
msgid ""
"The %(resource)s %(name)s does not have unique name. Please refer to "
"admin guide and create one."
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:113
#, python-format
msgid ""
"There is no %(resource)s %(name)s. Please refer to admin guide and create"
" one."
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:213
#, python-format
msgid "Error %s when creating service VM resources. Cleaning up."
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:321
#, python-format
msgid ""
"Failed to delete %(resource_name)s %(net_id)s for service vm due to "
"%(err)s"
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:453
#, python-format
msgid "Hosting port DB inconsistency for hosting device %s"
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:506
#, python-format
msgid "Port trunk pair DB inconsistency for port %s"
msgstr ""

#: neutron/plugins/cisco/models/virt_phy_sw_v2.py:280
#, python-format
msgid "Unable to delete port '%(pname)s' on switch. Exception: %(exp)s"
msgstr ""

#: neutron/plugins/embrane/base_plugin.py:106
#: neutron/plugins/embrane/agent/dispatcher.py:131
msgid "Unhandled exception occurred"
msgstr ""

#: neutron/plugins/embrane/base_plugin.py:171
#: neutron/plugins/embrane/base_plugin.py:190
#, python-format
msgid "The following routers have not physical match: %s"
msgstr ""

#: neutron/plugins/hyperv/agent/hyperv_neutron_agent.py:299
#: neutron/plugins/mlnx/agent/eswitch_neutron_agent.py:115
#, python-format
msgid "Unsupported network type %s"
msgstr ""

#: neutron/plugins/hyperv/agent/hyperv_neutron_agent.py:329
#, python-format
msgid "Port metrics raw enabling for port: %s"
msgstr ""

#: neutron/plugins/hyperv/agent/security_groups_driver.py:62
#, python-format
msgid "Hyper-V Exception: %(hyperv_exeption)s while adding rule: %(rule)s"
msgstr ""

#: neutron/plugins/hyperv/agent/security_groups_driver.py:72
#, python-format
msgid "Hyper-V Exception: %(hyperv_exeption)s while removing rule: %(rule)s"
msgstr ""

#: neutron/plugins/ibm/sdnve_api.py:176
#, python-format
msgid "Error: Could not reach server: %(url)s Exception: %(excp)s."
msgstr ""

#: neutron/plugins/ibm/sdnve_api.py:368
#, python-format
msgid "Did not find tenant: %r"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:234
#, python-format
msgid "Delete net failed after deleting the network in DB: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:351
#, python-format
msgid "Delete port operation failed in SDN-VE after deleting the port from DB: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:416
#, python-format
msgid ""
"Delete subnet operation failed in SDN-VE after deleting the subnet from "
"DB: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:497
#, python-format
msgid ""
"Delete router operation failed in SDN-VE after deleting the router in DB:"
" %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:541
msgid ""
"SdnvePluginV2._add_router_interface_only: failed to add the interface in "
"the roll back. of a remove_router_interface operation"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:661
#, python-format
msgid "Delete floatingip failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/agent/sdnve_neutron_agent.py:200
#, python-format
msgid ""
"Interface %(interface)s for physical network %(physical_network)s does "
"not exist. Agent terminated!"
msgstr ""

#: neutron/plugins/ibm/agent/sdnve_neutron_agent.py:261
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1551
#, python-format
msgid "%s Agent terminated!"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:183
#, python-format
msgid "Failed creating vxlan interface for %(segmentation_id)s"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:341
#, python-format
msgid "Unable to add %(interface)s to %(bridge_name)s! Exception: %(e)s"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:354
#, python-format
msgid "Unable to add vxlan interface for network %s"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:361
#, python-format
msgid "No mapping for physical network %s"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:370
#, python-format
msgid "Unknown network_type %(network_type)s for network %(network_id)s."
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:455
#, python-format
msgid "Cannot delete bridge %s, does not exist"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:534
msgid "No valid Segmentation ID to perform UCAST test."
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:575
msgid ""
"Linux kernel vxlan module and iproute2 3.8 or above are required to "
"enable VXLAN."
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:804
msgid "Unable to obtain MAC address for unique ID. Agent terminated!"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:1002
#: neutron/plugins/sriovnicagent/sriov_nic_agent.py:274
#, python-format
msgid "Error in agent loop. Devices info: %s"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:1025
#: neutron/plugins/mlnx/agent/eswitch_neutron_agent.py:404
#, python-format
msgid "Parsing physical_interface_mappings failed: %s. Agent terminated!"
msgstr ""

#: neutron/plugins/metaplugin/meta_neutron_plugin.py:223
#: neutron/plugins/metaplugin/meta_neutron_plugin.py:367
msgid "Failed to add flavor bindings"
msgstr ""

#: neutron/plugins/metaplugin/proxy_neutron_plugin.py:67
#, python-format
msgid "Update subnet failed: %s"
msgstr ""

#: neutron/plugins/metaplugin/proxy_neutron_plugin.py:95
#, python-format
msgid "Update network failed: %s"
msgstr ""

#: neutron/plugins/metaplugin/proxy_neutron_plugin.py:123
#, python-format
msgid "Update port failed: %s"
msgstr ""

#: neutron/plugins/midonet/plugin.py:187
#, python-format
msgid "There is no %(name)s with ID %(id)s in MidoNet."
msgstr ""

#: neutron/plugins/midonet/plugin.py:580
#, python-format
msgid "Failed to create a port on network %(net_id)s: %(err)s"
msgstr ""

#: neutron/plugins/midonet/plugin.py:597
#, python-format
msgid "There is no port with ID %(id)s in MidoNet."
msgstr ""

#: neutron/plugins/midonet/plugin.py:649
#, python-format
msgid "Failed to delete DHCP mapping for port %(id)s"
msgstr ""

#: neutron/plugins/midonet/plugin.py:1031
#, python-format
msgid ""
"Failed to create MidoNet resources to add router interface. "
"info=%(info)s, router_id=%(router_id)s"
msgstr ""

#: neutron/plugins/midonet/plugin.py:1148
#, python-format
msgid "Failed to create MidoNet resources for sg %(sg)r"
msgstr ""

#: neutron/plugins/ml2/db.py:205 neutron/plugins/ml2/db.py:291
#: neutron/plugins/ml2/plugin.py:1069
#, python-format
msgid "Multiple ports have port_id starting with %s"
msgstr ""

#: neutron/plugins/ml2/managers.py:53
#, python-format
msgid ""
"Type driver '%(new_driver)s' ignored because type driver '%(old_driver)s'"
" is already registered for type '%(type)s'"
msgstr ""

#: neutron/plugins/ml2/managers.py:69
#, python-format
msgid "No type driver for tenant network_type: %s. Service terminated!"
msgstr ""

#: neutron/plugins/ml2/managers.py:127
#, python-format
msgid "Network %s has no segments"
msgstr ""

#: neutron/plugins/ml2/managers.py:205 neutron/plugins/ml2/managers.py:232
#, python-format
msgid "Failed to release segment '%s' because network type is not supported."
msgstr ""

#: neutron/plugins/ml2/managers.py:295
#, python-format
msgid "Mechanism driver '%(name)s' failed in %(method)s"
msgstr ""

#: neutron/plugins/ml2/managers.py:597
#, python-format
msgid "Mechanism driver %s failed in bind_port"
msgstr ""

#: neutron/plugins/ml2/managers.py:656
#, python-format
msgid "Extension driver '%(name)s' failed in %(method)s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:266
#, python-format
msgid "Failed to commit binding results for %(port)s after %(max)s tries"
msgstr ""

#: neutron/plugins/ml2/plugin.py:398
#, python-format
msgid "Serialized vif_details DB value '%(value)s' for port %(port)s is invalid"
msgstr ""

#: neutron/plugins/ml2/plugin.py:409
#, python-format
msgid "Serialized profile DB value '%(value)s' for port %(port)s is invalid"
msgstr ""

#: neutron/plugins/ml2/plugin.py:512
#, python-format
msgid "mechanism_manager.create_network_postcommit failed, deleting network '%s'"
msgstr ""

#: neutron/plugins/ml2/plugin.py:648
#, python-format
msgid "Exception auto-deleting port %s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:656
#, python-format
msgid "Exception auto-deleting subnet %s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:665
msgid "mechanism_manager.delete_network_postcommit failed"
msgstr ""

#: neutron/plugins/ml2/plugin.py:682
#, python-format
msgid "mechanism_manager.create_subnet_postcommit failed, deleting subnet '%s'"
msgstr ""

#: neutron/plugins/ml2/plugin.py:764
#, python-format
msgid "Exception deleting fixed_ip from port %s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:774
msgid "mechanism_manager.delete_subnet_postcommit failed"
msgstr ""

#: neutron/plugins/ml2/plugin.py:810
#, python-format
msgid "mechanism_manager.create_port_postcommit failed, deleting port '%s'"
msgstr ""

#: neutron/plugins/ml2/plugin.py:822
#, python-format
msgid "_bind_port_if_needed failed, deleting port '%s'"
msgstr ""

#: neutron/plugins/ml2/plugin.py:908
#, python-format
msgid "No Host supplied to bind DVR Port %s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:1052
#, python-format
msgid "mechanism_manager.delete_port_postcommit failed for port %s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:1078
#, python-format
msgid "Binding info for DVR port %s not found"
msgstr ""

#: neutron/plugins/ml2/drivers/type_gre.py:75
msgid "Failed to parse tunnel_id_ranges. Service terminated!"
msgstr ""

#: neutron/plugins/ml2/drivers/type_gre.py:86
#, python-format
msgid "Skipping unreasonable gre ID range %(tun_min)s:%(tun_max)s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vlan.py:92
msgid "Failed to parse network_vlan_ranges. Service terminated!"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vxlan.py:82
msgid "Failed to parse vni_ranges. Service terminated!"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vxlan.py:92
#, python-format
msgid "Skipping unreasonable VXLAN VNI range %(tun_min)s:%(tun_max)s"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:147
msgid "Brocade Mechanism: failed to create network in db"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:183
msgid "Brocade NOS driver: failed in create network"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:213
msgid "Brocade Mechanism: failed to delete network in db"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:241
msgid "Brocade NOS driver: failed to delete network"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:282
msgid "Brocade Mechanism: failed to create port in db"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:314
#, python-format
msgid "Brocade NOS driver: failed to associate mac %s"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:337
msgid "Brocade Mechanism: failed to delete port in db"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:369
#, python-format
msgid "Brocade NOS driver: failed to dissociate MAC %s"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:85
msgid "Connect failed to switch"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:104
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:114
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:142
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:159
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:172
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:185
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:352
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:371
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:385
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:398
#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:411
msgid "NETCONF error"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_topology.py:111
msgid "APIC service agent: failed in reporting state"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_topology.py:197
#, python-format
msgid "No such interface (ignored): %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_topology.py:247
msgid "APIC service agent: exception in LLDP parsing"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_topology.py:302
#, python-format
msgid "APIC service agent: can not get MACaddr for %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_topology.py:318
msgid "APIC host agent: failed in reporting state"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_bigswitch/driver.py:110
msgid "Inconsistency with backend controller triggering full synchronization."
msgstr ""

#: neutron/plugins/ml2/drivers/mech_nuage/driver.py:92
#, python-format
msgid ""
"Refusing to bind port for segment ID %(id)s, segment %(seg)s, phys net "
"%(physnet)s, and network type %(nettype)s"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_sriov/mech_driver.py:87
msgid "Failed to parse supported PCI vendor devices"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:161
#, python-format
msgid "Invalid physical network type %(type)s. Server terminated!"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:169
#, python-format
msgid "Parsing physical_network_type failed: %s. Server terminated!"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:174
#, python-format
msgid ""
"Invalid physical network type %(type)s for network %(net)s. Server "
"terminated!"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:186
#, python-format
msgid "%s. Server terminated!"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:208
#, python-format
msgid "Invalid tenant_network_type: %s. Service terminated!"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:243
#, python-format
msgid "provider:network_type %s not supported"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:252
msgid "provider:segmentation_id specified for flat network"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:257
msgid "provider:segmentation_id required"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:260
#, python-format
msgid "provider:segmentation_id out of range (%(min_id)s through %(max_id)s)"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:268
msgid "provider:physical_network specified for local network"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:272
msgid "provider:segmentation_id specified for local network"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:283
#, python-format
msgid "Unknown provider:physical_network %s"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:289
msgid "provider:physical_network required"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:324
#, python-format
msgid "Unsupported vnic type %(vnic_type)s for physical network type %(net_type)s"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:328
msgid "Invalid vnic_type on port_create"
msgstr ""

#: neutron/plugins/mlnx/mlnx_plugin.py:330
msgid "vnic_type is not defined in port profile"
msgstr ""

#: neutron/plugins/mlnx/agent/eswitch_neutron_agent.py:57
#, python-format
msgid "Agent cache inconsistency - port id is not stored for %s"
msgstr ""

#: neutron/plugins/mlnx/agent/eswitch_neutron_agent.py:134
#, python-format
msgid "Unknown network type %(network_type)s for network %(network_id)s"
msgstr ""

#: neutron/plugins/mlnx/agent/eswitch_neutron_agent.py:372
msgid ""
"Request timeout in agent event loop eSwitchD is not responding - "
"exiting..."
msgstr ""

#: neutron/plugins/mlnx/agent/eswitch_neutron_agent.py:412
#, python-format
msgid "Failed on Agent initialisation : %s. Agent terminated!"
msgstr ""

#: neutron/plugins/mlnx/agent/utils.py:32
msgid ""
"Failed to import eventlet.green.zmq. Won't connect to eSwitchD - "
"exiting..."
msgstr ""

#: neutron/plugins/mlnx/agent/utils.py:75
#, python-format
msgid "Action %(action)s failed: %(reason)s"
msgstr ""

#: neutron/plugins/mlnx/agent/utils.py:77
#, python-format
msgid "Unknown operation status %s"
msgstr ""

#: neutron/plugins/nec/nec_plugin.py:247
#, python-format
msgid "create_ofc_port() failed due to %s"
msgstr ""

#: neutron/plugins/nec/nec_plugin.py:287
#, python-format
msgid "Failed to delete port=%(port)s from OFC: %(exc)s"
msgstr ""

#: neutron/plugins/nec/nec_plugin.py:323
#, python-format
msgid "Failed to create network id=%(id)s on OFC: %(exc)s"
msgstr ""

#: neutron/plugins/nec/nec_plugin.py:417
#, python-format
msgid "delete_network() failed due to %s"
msgstr ""

#: neutron/plugins/nec/nec_router.py:320
#, python-format
msgid ""
"default_router_provider %(default)s is supported! Please specify one of "
"%(supported)s"
msgstr ""

#: neutron/plugins/nec/nec_router.py:337
#, python-format
msgid ""
"No router provider is enabled. neutron-server terminated! "
"(supported=%(supported)s, configured=%(config)s)"
msgstr ""

#: neutron/plugins/nec/packet_filter.py:134
#: neutron/plugins/nec/packet_filter.py:186
#, python-format
msgid "Failed to create packet_filter id=%(id)s on OFC: %(exc)s"
msgstr ""

#: neutron/plugins/nec/packet_filter.py:218
#, python-format
msgid "Failed to delete packet_filter id=%(id)s from OFC: %(exc)s"
msgstr ""

#: neutron/plugins/nec/router_drivers.py:124
#, python-format
msgid "create_router() failed due to %s"
msgstr ""

#: neutron/plugins/nec/router_drivers.py:152
#, python-format
msgid "_update_ofc_routes() failed due to %s"
msgstr ""

#: neutron/plugins/nec/router_drivers.py:167
#, python-format
msgid "delete_router() failed due to %s"
msgstr ""

#: neutron/plugins/nec/router_drivers.py:199
#, python-format
msgid "add_router_interface() failed due to %s"
msgstr ""

#: neutron/plugins/nec/router_drivers.py:216
#, python-format
msgid "delete_router_interface() failed due to %s"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:55
#, python-format
msgid "Cannot complete the sync between Neutron and VSD because of error:%s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:101
msgid "Agent terminated!: Failed to get a datapath."
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:120
msgid "Agent terminated"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:157
msgid "Agent failed to create agent config map"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:445
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:471
#, python-format
msgid "No local VLAN available for net-id=%s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:460
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:509
#, python-format
msgid ""
"Cannot provision %(network_type)s network for net-id=%(net_uuid)s - "
"tunneling disabled"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:471
#, python-format
msgid ""
"Cannot provision %(network_type)s network for net-id=%(net_uuid)s - no "
"bridge for physical_network %(physical_network)s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:481
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:557
#, python-format
msgid ""
"Cannot provision unknown network type %(network_type)s for net-"
"id=%(net_uuid)s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:519
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:615
#, python-format
msgid ""
"Cannot reclaim unknown network type %(network_type)s for net-"
"id=%(net_uuid)s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:661
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1045
msgid "ofport should have a value that can be interpreted as an integer"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:664
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1048
#, python-format
msgid "Failed to set-up %(type)s tunnel port to %(ip)s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:842
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1395
msgid "Error while synchronizing tunnels"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:882
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1464
msgid "Error while processing VIF ports"
msgstr ""

#: neutron/plugins/oneconvergence/plugin.py:237
msgid "Failed to create subnet, deleting it from neutron"
msgstr ""

#: neutron/plugins/oneconvergence/plugin.py:301
#, python-format
msgid "Deleting newly created neutron port %s"
msgstr ""

#: neutron/plugins/oneconvergence/plugin.py:374
msgid "Failed to create floatingip"
msgstr ""

#: neutron/plugins/oneconvergence/plugin.py:413
msgid "Failed to create router"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:89
#, python-format
msgid "Login Failed: %s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:90
#, python-format
msgid "Unable to establish connection with Controller %s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:92
msgid "Retrying after 1 second..."
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:102
msgid "login failed"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:133
#, python-format
msgid "request: Request failed from Controller side :%s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:138
#, python-format
msgid "Response is Null, Request timed out: %(method)s to %(uri)s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:150
#, python-format
msgid ""
"Request %(method)s %(uri)s body = %(body)s failed with status %(status)s."
" Reason: %(reason)s)"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:159
#, python-format
msgid "%(method)s to %(url)s, unexpected response code: %(status)d"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:165
#, python-format
msgid "Request failed from Controller side with Status=%s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:159
msgid ""
"DVR: Failed to obtain a valid local DVR MAC address - L2 Agent operating "
"in Non-DVR Mode"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:329
#, python-format
msgid "DVR: Duplicate DVR router interface detected for subnet %s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:337
#, python-format
msgid "DVR: Unable to retrieve subnet information for subnet_id %s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:496
#, python-format
msgid "Centralized-SNAT port %s already seen on "
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:498
#, python-format
msgid "a different subnet %s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:336
msgid "No tunnel_type specified, cannot create tunnels"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:339
#, python-format
msgid "tunnel_type %s not supported by agent"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:528
#, python-format
msgid ""
"Cannot provision flat network for net-id=%(net_uuid)s - no bridge for "
"physical_network %(physical_network)s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:548
#, python-format
msgid ""
"Cannot provision VLAN network for net-id=%(net_uuid)s - no bridge for "
"physical_network %(physical_network)s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:763
msgid ""
"Failed to create OVS patch port. Cannot have tunneling enabled on this "
"agent, since this version of OVS does not support tunnels or patch ports."
" Agent terminated!"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:889
#, python-format
msgid ""
"Bridge %(bridge)s for physical network %(physical_network)s does not "
"exist. Agent terminated!"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1250
#, python-format
msgid ""
"process_network_ports - iteration:%d - failure while retrieving port "
"details from server"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1279
#, python-format
msgid ""
"process_ancillary_network_ports - iteration:%d - failure while retrieving"
" port details from server"
msgstr ""

#: neutron/plugins/sriovnicagent/eswitch_manager.py:47
#, python-format
msgid "Failed to get devices for %s"
msgstr ""

#: neutron/plugins/sriovnicagent/sriov_nic_agent.py:181
#, python-format
msgid "Failed to set device %s state"
msgstr ""

#: neutron/plugins/sriovnicagent/sriov_nic_agent.py:334
msgid "Failed on Agent configuration parse. Agent terminated!"
msgstr ""

#: neutron/plugins/sriovnicagent/sriov_nic_agent.py:348
msgid "Agent Initialization Failed"
msgstr ""

#: neutron/plugins/vmware/api_client/base.py:184
#, python-format
msgid "Login request for an invalid connection: '%s'"
msgstr ""

#: neutron/plugins/vmware/api_client/client.py:103
#, python-format
msgid "Request timed out: %(method)s to %(url)s"
msgstr ""

#: neutron/plugins/vmware/api_client/client.py:114
#, python-format
msgid "Received error code: %s"
msgstr ""

#: neutron/plugins/vmware/api_client/client.py:115
#, python-format
msgid "Server Error Message: %s"
msgstr ""

#: neutron/plugins/vmware/api_client/client.py:121
#, python-format
msgid ""
"%(method)s to %(url)s, unexpected response code: %(status)d (content = "
"'%(body)s')"
msgstr ""

#: neutron/plugins/vmware/api_client/client.py:138
msgid "Unable to determine NSX version. Plugin might not work as expected."
msgstr ""

#: neutron/plugins/vmware/api_client/eventlet_client.py:146
#, python-format
msgid "Login error \"%s\""
msgstr ""

#: neutron/plugins/vmware/common/sync.py:621
#, python-format
msgid ""
"An error occurred while communicating with NSX backend. Will retry "
"synchronization in %d seconds"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:72
#, python-format
msgid "Unable to find Logical Service Node for network %s."
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:112
#, python-format
msgid ""
"Unable to find Logical Service Node Port for LSN %(lsn_id)s and subnet "
"%(subnet_id)s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:139
#, python-format
msgid ""
"Unable to find Logical Service Node Port for LSN %(lsn_id)s and mac "
"address %(mac)s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:320
#, python-format
msgid "Error while configuring LSN port %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/migration.py:82
#, python-format
msgid "Port %s is already gone"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/nsx.py:137
#, python-format
msgid ""
"Error while creating subnet %(cidr)s for network %(network)s. Please, "
"contact administrator"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/nsx.py:242
#, python-format
msgid "Error while configuring DHCP for port %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/rpc.py:124
#, python-format
msgid ""
"An error occurred while operating on the metadata access network for "
"router:'%s'"
msgstr ""

#: neutron/plugins/vmware/nsxlib/router.py:257
#, python-format
msgid "Cannot update NSX routes %(routes)s for router %(router_id)s"
msgstr ""

#: neutron/plugins/vmware/nsxlib/switch.py:151
#: neutron/plugins/vmware/nsxlib/switch.py:166
#, python-format
msgid "Network not found, Error: %s"
msgstr ""

#: neutron/plugins/vmware/nsxlib/switch.py:189
msgid "Port or Network not found"
msgstr ""

#: neutron/plugins/vmware/nsxlib/switch.py:299
#: neutron/plugins/vmware/nsxlib/switch.py:330
#, python-format
msgid "Port or Network not found, Error: %s"
msgstr ""

#: neutron/plugins/vmware/nsxlib/switch.py:372
#, python-format
msgid "Port not found, Error: %s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:212
#, python-format
msgid "Unable to process default l2 gw service: %s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:250
#, python-format
msgid "Unable to create port on NSX logical router %s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:339
#, python-format
msgid ""
"Unable to plug attachment in NSX logical router port %(r_port_id)s, "
"associated with Neutron %(q_port_id)s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:431
#, python-format
msgid ""
"An exception occurred while creating the neutron port %s on the NSX "
"plaform"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:538
#, python-format
msgid ""
"Ignoring exception as this means the peer for port '%s' has already been "
"deleted."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:892
#, python-format
msgid "Maximum number of logical ports reached for logical network %s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1172
msgid "Unable to create port or set port attachment in NSX."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1295
#, python-format
msgid "Unable to update port id: %s."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1395
#, python-format
msgid ""
"Unable to create L3GW port on logical router %(router_uuid)s. Verify "
"Default Layer-3 Gateway service %(def_l3_gw_svc)s id is correct"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1760
#, python-format
msgid "Logical router resource %s not found on NSX platform"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1796
#, python-format
msgid ""
"An error occurred while removing NAT rules on the NSX platform for "
"floating ip:%s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1943
#, python-format
msgid ""
"An error occurred while creating NAT rules on the NSX platform for "
"floating ip:%(floating_ip)s mapped to internal ip:%(internal_ip)s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2055
msgid ""
"Unable to remove gateway service from NSX plaform - the resource was not "
"found"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2111
#, python-format
msgid ""
"Rolling back database changes for gateway device %s because of an error "
"in the NSX backend"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2298
#, python-format
msgid ""
"Removal of gateway device: %(neutron_id)s failed on NSX backend (NSX "
"id:%(nsx_id)s). Neutron and NSX states have diverged."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2346
#, python-format
msgid ""
"Error while updating security profile %(uuid)s with name %(name)s: "
"%(error)s."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2387
#, python-format
msgid ""
"An exception occurred while removing the NSX security profile "
"%(sec_profile_id)s, associated with Netron security group "
"%(sec_group_id)s"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:897
#, python-format
msgid "Failed to create firewall on vShield Edge bound on router %s"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:904
msgid "Bad Firewall request Input"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1125
#, python-format
msgid "Failed to find the edge with vip_id: %s"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1196
#, python-format
msgid "Failed to create healthmonitor associated with pool id: %s!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1213
msgid "Failed to create pool on vshield edge"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1273
msgid "Failed to create vip!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1313
#, python-format
msgid "Failed to update vip with id: %s!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1330
#, python-format
msgid "Failed to delete vip with id: %s!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1386
#, python-format
msgid "Failed to update pool with id: %s!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1408
#: neutron/plugins/vmware/plugins/service.py:1455
#: neutron/plugins/vmware/plugins/service.py:1478
msgid "Failed to update pool with the member"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1434
msgid "Failed to update old pool with the member"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1498
#, python-format
msgid "Failed to update monitor with id: %s!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1537
msgid "Failed to associate monitor with pool!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1568
msgid "Failed to update pool with pool_monitor!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1610
msgid "Bad or unsupported Input request!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1613
#, python-format
msgid ""
"Failed to update ipsec VPN configuration with vpnservice: "
"%(vpnservice_id)s on vShield Edge: %(edge_id)s"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1765
#, python-format
msgid "Router %s not found"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:132
#, python-format
msgid ""
"VCNS: Failed to get edge status:\n"
"%s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:164
#, python-format
msgid ""
"VCNS: Failed to update vnic %(config)s:\n"
"%(response)s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:170
#, python-format
msgid "VCNS: Failed to update vnic %d"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:221
#, python-format
msgid "VCNS: deploy edge failed for router %s."
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:240
#, python-format
msgid "VCNS: Edge %s status query failed."
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:246
#, python-format
msgid "VCNS: Unable to retrieve edge %(edge_id)s status. Retry %(retries)d."
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:252
#, python-format
msgid "VCNS: Unable to retrieve edge %s status. Abort."
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:262
#, python-format
msgid "VCNS: Failed to deploy edge %(edge_id)s for %(name)s, status %(status)d"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:284
#, python-format
msgid ""
"VCNS: Failed to delete %(edge_id)s:\n"
"%(response)s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:289
#, python-format
msgid "VCNS: Failed to delete %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:299
#, python-format
msgid ""
"VCNS: Failed to get edges:\n"
"%s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:378
#, python-format
msgid ""
"VCNS: Failed to get nat config:\n"
"%s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:401
#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:526
#, python-format
msgid ""
"VCNS: Failed to create snat rule:\n"
"%s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:443
#, python-format
msgid ""
"VCNS: Failed to delete snat rule:\n"
"%s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:596
#, python-format
msgid ""
"VCNS: Failed to update routes:\n"
"%s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:648
msgid "Failed to get service config"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:660
msgid "Failed to enable loadbalancer service config"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:190
#, python-format
msgid "Failed to get firewall with edge id: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:218
#, python-format
msgid "Failed to get firewall rule: %(rule_id)s with edge_id: %(edge_id)s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:234
#, python-format
msgid "Failed to update firewall with edge_id: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:246
#, python-format
msgid "Failed to delete firewall with edge_id:%s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:260
#, python-format
msgid "Failed to update firewall rule: %(rule_id)s with edge_id: %(edge_id)s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:273
#, python-format
msgid "Failed to delete firewall rule: %(rule_id)s with edge_id: %(edge_id)s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:290
#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:318
#, python-format
msgid "Failed to add firewall rule above: %(rule_id)s with edge_id: %(edge_id)s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:329
#, python-format
msgid "Failed to append a firewall rulewith edge_id: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_ipsecvpn_driver.py:138
#, python-format
msgid "Failed to update ipsec vpn configuration with edge_id: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_ipsecvpn_driver.py:149
#, python-format
msgid "Failed to delete ipsec vpn configuration with edge_id: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:183
#, python-format
msgid "Failed to create app profile on edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:194
#, python-format
msgid "Failed to create vip on vshield edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:229
msgid "Failed to get vip on edge"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:246
#, python-format
msgid "Failed to update app profile on edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:254
#, python-format
msgid "Failed to update vip on edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:265
#, python-format
msgid "vip not found on edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:268
#, python-format
msgid "Failed to delete vip on edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:273
#, python-format
msgid "app profile not found on edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:276
#, python-format
msgid "Failed to delete app profile on edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:287
msgid "Failed to create pool"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:314
msgid "Failed to get pool on edge"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:326
msgid "Failed to update pool"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:336
msgid "Failed to delete pool"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:346
#, python-format
msgid "Failed to create monitor on edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:374
#, python-format
msgid "Failed to get monitor on edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:391
#, python-format
msgid "Failed to update monitor on edge: %s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:402
msgid "Failed to delete monitor"
msgstr ""

#: neutron/plugins/vmware/vshield/tasks/tasks.py:97
#, python-format
msgid "Task %(task)s encountered exception in %(func)s at state %(state)s"
msgstr ""

#: neutron/plugins/vmware/vshield/tasks/tasks.py:187
#: neutron/plugins/vmware/vshield/tasks/tasks.py:206
#: neutron/plugins/vmware/vshield/tasks/tasks.py:228
#, python-format
msgid "Task %(task)s encountered exception in %(cb)s"
msgstr ""

#: neutron/plugins/vmware/vshield/tasks/tasks.py:318
msgid "TaskManager terminating because of an exception"
msgstr ""

#: neutron/plugins/vmware/vshield/tasks/tasks.py:372
msgid "Exception in _check_pending_tasks"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:285
#, python-format
msgid "Not enough candidates, a HA router needs at least %s agents"
msgstr ""

#: neutron/services/service_base.py:88
#, python-format
msgid "Error loading provider '%(provider)s' for service %(service_type)s"
msgstr ""

#: neutron/services/firewall/fwaas_plugin.py:24
msgid "Firewall service plugin requires neutron-fwaas module"
msgstr ""

#: neutron/services/firewall/agents/l3reference/firewall_l3_agent.py:144
#, python-format
msgid "Firewall Driver Error for %(func_name)s for fw: %(fwid)s"
msgstr ""

#: neutron/services/firewall/agents/l3reference/firewall_l3_agent.py:159
#, python-format
msgid "FWaaS RPC failure in %(func_name)s for fw: %(fwid)s"
msgstr ""

#: neutron/services/firewall/agents/l3reference/firewall_l3_agent.py:179
#: neutron/services/firewall/agents/l3reference/firewall_l3_agent.py:198
#, python-format
msgid "Firewall Driver Error on fw state %(fwmsg)s for fw: %(fwid)s"
msgstr ""

#: neutron/services/firewall/agents/l3reference/firewall_l3_agent.py:238
#, python-format
msgid "FWaaS RPC info call failed for '%s'."
msgstr ""

#: neutron/services/firewall/agents/l3reference/firewall_l3_agent.py:282
msgid "Failed fwaas process services sync"
msgstr ""

#: neutron/services/l3_router/l3_arista.py:113
#, python-format
msgid "Error creating router on Arista HW router=%s "
msgstr ""

#: neutron/services/l3_router/l3_arista.py:136
#, python-format
msgid "Error updating router on Arista HW router=%s "
msgstr ""

#: neutron/services/l3_router/l3_arista.py:151
#, python-format
msgid "Error deleting router on Arista HW router %(r)s exception=%(e)s"
msgstr ""

#: neutron/services/l3_router/l3_arista.py:197
#, python-format
msgid "Error Adding subnet %(subnet)s to router %(router_id)s on Arista HW"
msgstr ""

#: neutron/services/l3_router/l3_arista.py:231
#, python-format
msgid ""
"Error removing interface %(interface)s from router %(router_id)s on "
"Arista HWException =(exc)s"
msgstr ""

#: neutron/services/l3_router/l3_arista.py:277
#, python-format
msgid "Error Adding interface %(subnet_id)s to router %(router_id)s on Arista HW"
msgstr ""

#: neutron/services/l3_router/brocade/l3_router_plugin.py:177
#, python-format
msgid ""
"Failed to create Brocade resources to add router interface. "
"info=%(info)s, router_id=%(router_id)s"
msgstr ""

#: neutron/services/l3_router/brocade/l3_router_plugin.py:223
#, python-format
msgid ""
"Fail remove of interface from brocade router interface. info=%(info)s, "
"router_id=%(router_id)s"
msgstr ""

#: neutron/services/loadbalancer/plugin.py:24
msgid "Loadbalancer service plugin requires neutron-lbaas module"
msgstr ""

#: neutron/services/metering/agents/metering_agent.py:180
#, python-format
msgid "Driver %(driver)s does not implement %(func)s"
msgstr ""

#: neutron/services/metering/agents/metering_agent.py:184
#, python-format
msgid "Driver %(driver)s:%(func)s runtime error"
msgstr ""

#: neutron/services/vpn/plugin.py:24
msgid "VPN service plugin requires neutron-vpnaas module"
msgstr ""

#: neutron/tests/unit/cisco/l3/device_handling_test_support.py:99
#, python-format
msgid "Failed to delete port %(p_id)s for vm instance %(v_id)s due to %(err)s"
msgstr ""

